---

- name: validate vars
  include_tasks: tasks/variables.yml

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: 
    - state|default('present') == 'present'
    - download | default('true') | bool

- name: deploy 
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-deploy.yml"
  when: 
    - state|default('present') == 'present'
    - deploy | default('true') | bool

- name: install carplay service (darwin only)
  include_tasks: tasks/darwin-carplay.yml
  when:
    - state|default('present') == 'present'
    - deploy | default('true') | bool
    - carplay_service_enabled | default(false) | bool
    - (ansible_os_family | os_family_to_os_type) == 'darwin'
    - ansible_architecture == 'arm64'

- name: track versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-track-versions.yml"
  when:
    - state|default('present') == 'present'
    - deploy | default('true') | bool

- name: remove archived versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-remove-archived.yml"
  when: 
    - state|default('present') == 'present'
    - deploy | default('true') | bool

- name: maintain supervision files
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-maintain-supervision.yml"
  when: 
    - state|default('present') == 'present'
    - maintain_supervision_files | default('no') | bool
    - deploy | default('true') | bool

- name: clear temp folder
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-clear-temp.yml"
  when: 
    - clear_temp_folder | default('no') | bool
    - deploy | default('true') | bool

- name: uninstall carplay service (darwin only)
  include_tasks: tasks/darwin-carplay-uninstall.yml
  when:
    - state|default('present') == 'absent'
    - carplay_service_enabled | default(false) | bool
    - (ansible_os_family | os_family_to_os_type) == 'darwin'
    - ansible_architecture == 'arm64'

- name: uninstall
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-uninstall.yml"
  when: state|default('present') == 'absent'

- name: set-facts for next steps
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-set-facts.yml"